# Site Information
title               : "Garage Roof"
phone               : "08000-418-212"
google-analytics-id : "?"

# Where things are
source              : .
destination         : ./_site

# Plugins
whitelist           : []
plugins             : ["jekyll-seo-tag", "jekyll-datapage-generator"]

# page_gen-dirs: false
# page_gen:
#     -
#         data: city
#         template: services/blocked-drains
#         name: Town
#         name_expr: '+ "blocked-drains-" + record[''Town'']'
#         dir: /
#     -
#         data: city
#         template: services/blocked-baths
#         name: Town
#         name_expr: '+ "blocked-baths-" + record[''Town'']'
#         dir: /
#     -
#         data: city
#         template: services/blocked-sinks
#         name: Town
#         name_expr: '+ "blocked-sinks-" + record[''Town'']'
#         dir: /
#     -
#         data: city
#         template: services/blocked-toilets
#         name: Town
#         name_expr: '+ "blocked-toilets-" + record[''Town'']'
#         dir: /
#     -
#         data: city
#         template: services/cctv-drains-survey
#         name: Town
#         name_expr: '+ "cctv-drains-survey-" + record[''Town'']'
#         dir: /
#     -
#         data: city
#         template: services/home-buyers-drain-survey
#         name: Town
#         name_expr: '+ "home-buyers-drain-survey-" + record[''Town'']'
#         dir: /
#     -
#         data: city
#         template: services/manhole-inspections
#         name: Town
#         name_expr: '+ "manhole-inspections-" + record[''Town'']'
#         dir: /
#     -
#         data: city
#         template: services/drain-cleaning
#         name: Town
#         name_expr: '+ "drain-cleaning-" + record[''Town'']'
#         dir: /
#     -
#         data: city
#         template: services/drain-inspection
#         name: Town
#         name_expr: '+ "drain-inspection-" + record[''Town'']'
#         dir: /
#     -
#         data: city
#         template: services/drain-jetting
#         name: Town
#         name_expr: '+ "drain-jetting-" + record[''Town'']'
#         dir: /
#     -
#         data: city
#         template: services/drain-jet-vacuumation
#         name: Town
#         name_expr: '+ "drain-jet-vacuumation-" + record[''Town'']'
#         dir: /
#     -
#         data: city
#         template: services/drain-relining
#         name: Town
#         name_expr: '+ "drain-relining-" + record[''Town'']'
#         dir: /
#     -
#         data: city
#         template: services/drain-repairs
#         name: Town
#         name_expr: '+ "drain-repairs-" + record[''Town'']'
#         dir: /
#     -
#         data: city
#         template: services/drainage-survey
#         name: Town
#         name_expr: '+ "drainage-survey-" + record[''Town'']'
#         dir: /
#     -
#         data: city
#         template: services/drain-unblocking
#         name: Town
#         name_expr: '+ "drain-unblocking-" + record[''Town'']'
#         dir: /
#     -
#         data: city
#         template: services/blocked-sewer
#         name: Town
#         name_expr: '+ "blocked-sewer-" + record[''Town'']'
#         dir: /
#     -
#         data: city
#         template: services/sewer-desilting
#         name: Town
#         name_expr: '+ "sewer-desilting-" + record[''Town'']'
#         dir: /
#     -
#         data: city
#         template: services/sewer-inspections
#         name: Town
#         name_expr: '+ "sewer-inspections-" + record[''Town'']'
#         dir: /
#     -
#         data: city
#         template: services/sewer-jet-vacuumation
#         name: Town
#         name_expr: '+ "sewer-jet-vacuumation-" + record[''Town'']'
#         dir: /
#     -
#         data: city
#         template: services/sewer-rehabilitations
#         name: Town
#         name_expr: '+ "sewer-rehabilitations-" + record[''Town'']'
#         dir: /
#     -
#         data: city
#         template: services/sewer-renovation
#         name: Town
#         name_expr: '+ "sewer-renovation-" + record[''Town'']'
#         dir: /
#     -
#         data: city
#         template: services/sewer-repairs
#         name: Town
#         name_expr: '+ "sewer-repairs-" + record[''Town'']'
#         dir: /
#     -
#         data: city
#         template: services/sewer-relining
#         name: Town
#         name_expr: '+ "sewer-relining-" + record[''Town'']'
#         dir: /
#     -
#         data: city
#         template: services/structural-coating
#         name: Town
#         name_expr: '+ "structural-coating-" + record[''Town'']'
#         dir: /

# Serving
detach              : false
port                : 4000
host                : 127.0.0.1
baseurl             : "https://adyanmuhammad.github.io/mass-city-2/"
show_dir_listing    : false
